title: Jonathan P. Shea
email: jonathanpshea@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Jon Shea and this is my personal page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jps359
facebook_username: jonathanpshea

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
